package br.com.ablebit.clj.config;

public enum ConfigurationProperty {
	
	RECEPTOR_IP,
	RECEPTOR_PORT,
	RECEPTOR_REPOSITORY_BUFFER_SIZE,
	RECEPTOR_REPOSITORY_DELAY,
	RECEPTOR_AUDIO_SAMPLERATE,
	RECEPTOR_AUDIO_SAMPLESIZE,
	RECEPTOR_AUDIO_CHANELS,
	RECEPTOR_AUDIO_SIGNED,
	RECEPTOR_AUDIO_BIGENDIAN,
	
	TRANSMISSOR_REMOTE_RECEPTOR_IP,
	TRANSMISSOR_REMOTE_RECEPTOR_PORT,
	TRANSMISSOR_AUDIO_MIN_VOLUME_RMS,
	TRANSMISSOR_AUDIO_SAMPLERATE,
	TRANSMISSOR_AUDIO_SAMPLESIZE,
	TRANSMISSOR_AUDIO_CHANELS,
	TRANSMISSOR_AUDIO_SIGNED,
	TRANSMISSOR_AUDIO_BIGENDIAN;

}
